# Generated by Django 4.1.3 on 2024-04-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='claim',
            table='claim_data',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
