# Generated by Django 4.1.3 on 2024-04-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_claim_table_alter_user_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Claim',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
