# Generated by Django 4.1.3 on 2024-04-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Claim',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
