# Generated by Django 4.1.12 on 2024-04-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
